#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const sources = [
    'sdk/textOps.js',
    'sdk/peerColors.js',
    'sdk/onlineDslLayer.js',
]

const chunks = sources.map((relativePath) => {
    const source = readFileSync(join(root, relativePath), 'utf8')
    return [
        `// ${relativePath}`,
        source
            .replace(/^import\s+\{[^}]+\}\s+from\s+['"][^'"]+['"]\n/gm, '')
            .trim(),
    ].join('\n')
})

const output = [
    '// Auto-generated by scripts/build-sdk.mjs. Do not edit by hand.',
    ...chunks,
    '',
].join('\n\n')

mkdirSync(join(root, 'dist'), { recursive: true })
writeFileSync(join(root, 'dist/index.js'), output)
